//funcion para añadir las cabeceras de la tabla
function aniadeCabeceras(tr){
    let tdCantidad=document.createElement("th");
    tdCantidad.textContent="Catidad";
    tr.appendChild(tdCantidad);
    let tdAlineacion=document.createElement("th");
    tdAlineacion.textContent="Alineacion";
    tr.appendChild(tdAlineacion);
    let tdPrecio=document.createElement("th");
    tdPrecio.textContent="Precio";
    tr.appendChild(tdPrecio);
    let tdMovimiento=document.createElement("th");
    tdMovimiento.textContent="MV";
    tr.appendChild(tdMovimiento);
    let tdFuerza=document.createElement("th");
    tdFuerza.textContent="FU";
    tr.appendChild(tdFuerza);
    let tdAgilidad=document.createElement("th");
    tdAgilidad.textContent="AG";
    tr.appendChild(tdAgilidad);
    let tdPase=document.createElement("th");
    tdPase.textContent="PS";
    tr.appendChild(tdPase);
    let tdArmadura=document.createElement("th");
    tdArmadura.textContent="AR";
    tr.appendChild(tdArmadura);
    let tdHabilidades=document.createElement("th");
    tdHabilidades.textContent="Habilidades";
    tr.appendChild(tdHabilidades);
    let tdPrincipal=document.createElement("th");
    tdPrincipal.textContent="Principal";
    tr.appendChild(tdPrincipal);
    let tdSecundaria=document.createElement("th");
    tdSecundaria.textContent="Secundaria";
    tr.appendChild(tdSecundaria);
}

//funcion para crear la tabla del equipo humano
function tablaHumanos(tabla){
    //linea
    tr=document.createElement("tr");
    let tdCantidad=document.createElement("td");
    let tdAlineacion=document.createElement("td");
    let tdPrecio=document.createElement("td");
    let tdMovimiento=document.createElement("td");
    let tdFuerza=document.createElement("td");
    let tdAgilidad=document.createElement("td");
    let tdPase=document.createElement("td");
    let tdArmadura=document.createElement("td");
    let tdHabilidades=document.createElement("td");
    let tdPrincipal=document.createElement("td");
    let tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-16";
    tdAlineacion.textContent="Linea";
    tdPrecio.textContent="50k";
    tdMovimiento.textContent="6";
    tdFuerza.textContent="3";
    tdAgilidad.textContent="3+";
    tdPase.textContent="4+";
    tdArmadura.textContent="9+";
    tdHabilidades.textContent="-";
    tdPrincipal.textContent="G";
    tdSecundaria.textContent="AF";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
    //Thrower
    tr=document.createElement("tr");
    tdCantidad=document.createElement("td");
    tdAlineacion=document.createElement("td");
    tdPrecio=document.createElement("td");
    tdMovimiento=document.createElement("td");
    tdFuerza=document.createElement("td");
    tdAgilidad=document.createElement("td");
    tdPase=document.createElement("td");
    tdArmadura=document.createElement("td");
    tdHabilidades=document.createElement("td");
    tdPrincipal=document.createElement("td");
    tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-2";
    tdAlineacion.textContent="Thrower";
    tdPrecio.textContent="80k";
    tdMovimiento.textContent="6";
    tdFuerza.textContent="3";
    tdAgilidad.textContent="3+";
    tdPase.textContent="2+";
    tdArmadura.textContent="9+";
    tdHabilidades.textContent="Manos seguras, Pasar";
    tdPrincipal.textContent="GP";
    tdSecundaria.textContent="AF";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
    //Catcher
    tr=document.createElement("tr");
    tdCantidad=document.createElement("td");
    tdAlineacion=document.createElement("td");
    tdPrecio=document.createElement("td");
    tdMovimiento=document.createElement("td");
    tdFuerza=document.createElement("td");
    tdAgilidad=document.createElement("td");
    tdPase=document.createElement("td");
    tdArmadura=document.createElement("td");
    tdHabilidades=document.createElement("td");
    tdPrincipal=document.createElement("td");
    tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-4";
    tdAlineacion.textContent="Catcher";
    tdPrecio.textContent="65k";
    tdMovimiento.textContent="8";
    tdFuerza.textContent="2";
    tdAgilidad.textContent="3+";
    tdPase.textContent="5+";
    tdArmadura.textContent="8+";
    tdHabilidades.textContent="Atrapar, Esquivar";
    tdPrincipal.textContent="AG";
    tdSecundaria.textContent="PF";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
    //Blitcher
    tr=document.createElement("tr");
    tdCantidad=document.createElement("td");
    tdAlineacion=document.createElement("td");
    tdPrecio=document.createElement("td");
    tdMovimiento=document.createElement("td");
    tdFuerza=document.createElement("td");
    tdAgilidad=document.createElement("td");
    tdPase=document.createElement("td");
    tdArmadura=document.createElement("td");
    tdHabilidades=document.createElement("td");
    tdPrincipal=document.createElement("td");
    tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-4";
    tdAlineacion.textContent="Blitcher";
    tdPrecio.textContent="85k";
    tdMovimiento.textContent="7";
    tdFuerza.textContent="3";
    tdAgilidad.textContent="3+";
    tdPase.textContent="4+";
    tdArmadura.textContent="9+";
    tdHabilidades.textContent="Placar";
    tdPrincipal.textContent="GF";
    tdSecundaria.textContent="AP";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
    //Halfling
    tr=document.createElement("tr");
    tdCantidad=document.createElement("td");
    tdAlineacion=document.createElement("td");
    tdPrecio=document.createElement("td");
    tdMovimiento=document.createElement("td");
    tdFuerza=document.createElement("td");
    tdAgilidad=document.createElement("td");
    tdPase=document.createElement("td");
    tdArmadura=document.createElement("td");
    tdHabilidades=document.createElement("td");
    tdPrincipal=document.createElement("td");
    tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-3";
    tdAlineacion.textContent="Halfling";
    tdPrecio.textContent="30k";
    tdMovimiento.textContent="5";
    tdFuerza.textContent="2";
    tdAgilidad.textContent="3+";
    tdPase.textContent="4+";
    tdArmadura.textContent="7+";
    tdHabilidades.textContent="Escurridizo, Esquivar, Humanoide bala";
    tdPrincipal.textContent="A";
    tdSecundaria.textContent="GF";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
    //Ogre
    tr=document.createElement("tr");
    tdCantidad=document.createElement("td");
    tdAlineacion=document.createElement("td");
    tdPrecio=document.createElement("td");
    tdMovimiento=document.createElement("td");
    tdFuerza=document.createElement("td");
    tdAgilidad=document.createElement("td");
    tdPase=document.createElement("td");
    tdArmadura=document.createElement("td");
    tdHabilidades=document.createElement("td");
    tdPrincipal=document.createElement("td");
    tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-1";
    tdAlineacion.textContent="Ogre";
    tdPrecio.textContent="140k";
    tdMovimiento.textContent="5";
    tdFuerza.textContent="5";
    tdAgilidad.textContent="4+";
    tdPase.textContent="5+";
    tdArmadura.textContent="10+";
    tdHabilidades.textContent="Estúpido, Solitario (4+), Golpe mortífero(+1), Cabeza dura, Lanzar compañero";
    tdPrincipal.textContent="F";
    tdSecundaria.textContent="AG";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
}

//funcion para crear la tabla del equipo orco
function tablaOrcos(tabla){
    //linea
    tr=document.createElement("tr");
    let tdCantidad=document.createElement("td");
    let tdAlineacion=document.createElement("td");
    let tdPrecio=document.createElement("td");
    let tdMovimiento=document.createElement("td");
    let tdFuerza=document.createElement("td");
    let tdAgilidad=document.createElement("td");
    let tdPase=document.createElement("td");
    let tdArmadura=document.createElement("td");
    let tdHabilidades=document.createElement("td");
    let tdPrincipal=document.createElement("td");
    let tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-16";
    tdAlineacion.textContent="Orco Linea";
    tdPrecio.textContent="50k";
    tdMovimiento.textContent="5";
    tdFuerza.textContent="3";
    tdAgilidad.textContent="3+";
    tdPase.textContent="4+";
    tdArmadura.textContent="10+";
    tdHabilidades.textContent="Animosidad (Orco Linea)";
    tdPrincipal.textContent="G";
    tdSecundaria.textContent="AF";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
    //Thrower
    tr=document.createElement("tr");
    tdCantidad=document.createElement("td");
    tdAlineacion=document.createElement("td");
    tdPrecio=document.createElement("td");
    tdMovimiento=document.createElement("td");
    tdFuerza=document.createElement("td");
    tdAgilidad=document.createElement("td");
    tdPase=document.createElement("td");
    tdArmadura=document.createElement("td");
    tdHabilidades=document.createElement("td");
    tdPrincipal=document.createElement("td");
    tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-2";
    tdAlineacion.textContent="Thrower";
    tdPrecio.textContent="65k";
    tdMovimiento.textContent="5";
    tdFuerza.textContent="3";
    tdAgilidad.textContent="3+";
    tdPase.textContent="3+";
    tdArmadura.textContent="9+";
    tdHabilidades.textContent="Animosidad (todo el equipo),Manos seguras, Pasar";
    tdPrincipal.textContent="GP";
    tdSecundaria.textContent="AF";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
    //Blitcher
    tr=document.createElement("tr");
    tdCantidad=document.createElement("td");
    tdAlineacion=document.createElement("td");
    tdPrecio=document.createElement("td");
    tdMovimiento=document.createElement("td");
    tdFuerza=document.createElement("td");
    tdAgilidad=document.createElement("td");
    tdPase=document.createElement("td");
    tdArmadura=document.createElement("td");
    tdHabilidades=document.createElement("td");
    tdPrincipal=document.createElement("td");
    tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-4";
    tdAlineacion.textContent="Blitcher";
    tdPrecio.textContent="80k";
    tdMovimiento.textContent="6";
    tdFuerza.textContent="3";
    tdAgilidad.textContent="3+";
    tdPase.textContent="4+";
    tdArmadura.textContent="10+";
    tdHabilidades.textContent="Animosidad (todo el equipo), Placar";
    tdPrincipal.textContent="GF";
    tdSecundaria.textContent="AP";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
    //Big Un Blocker
    tr=document.createElement("tr");
    tdCantidad=document.createElement("td");
    tdAlineacion=document.createElement("td");
    tdPrecio=document.createElement("td");
    tdMovimiento=document.createElement("td");
    tdFuerza=document.createElement("td");
    tdAgilidad=document.createElement("td");
    tdPase=document.createElement("td");
    tdArmadura=document.createElement("td");
    tdHabilidades=document.createElement("td");
    tdPrincipal=document.createElement("td");
    tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-4";
    tdAlineacion.textContent="Big Un Blocker";
    tdPrecio.textContent="90k";
    tdMovimiento.textContent="5";
    tdFuerza.textContent="4";
    tdAgilidad.textContent="4+";
    tdPase.textContent="-";
    tdArmadura.textContent="10+";
    tdHabilidades.textContent="Animosidad (Big Un Blocker)";
    tdPrincipal.textContent="GF";
    tdSecundaria.textContent="A";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
    //Goblin
    tr=document.createElement("tr");
    tdCantidad=document.createElement("td");
    tdAlineacion=document.createElement("td");
    tdPrecio=document.createElement("td");
    tdMovimiento=document.createElement("td");
    tdFuerza=document.createElement("td");
    tdAgilidad=document.createElement("td");
    tdPase=document.createElement("td");
    tdArmadura=document.createElement("td");
    tdHabilidades=document.createElement("td");
    tdPrincipal=document.createElement("td");
    tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-4";
    tdAlineacion.textContent="Halfling";
    tdPrecio.textContent="40k";
    tdMovimiento.textContent="6";
    tdFuerza.textContent="2";
    tdAgilidad.textContent="3+";
    tdPase.textContent="4+";
    tdArmadura.textContent="8+";
    tdHabilidades.textContent="Escurridizo, Esquivar, Humanoide bala";
    tdPrincipal.textContent="A";
    tdSecundaria.textContent="GF";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
    //Untrained Troll
    tr=document.createElement("tr");
    tdCantidad=document.createElement("td");
    tdAlineacion=document.createElement("td");
    tdPrecio=document.createElement("td");
    tdMovimiento=document.createElement("td");
    tdFuerza=document.createElement("td");
    tdAgilidad=document.createElement("td");
    tdPase=document.createElement("td");
    tdArmadura=document.createElement("td");
    tdHabilidades=document.createElement("td");
    tdPrincipal=document.createElement("td");
    tdSecundaria=document.createElement("td");
    tdCantidad.textContent="0-1";
    tdAlineacion.textContent="Untrained Troll";
    tdPrecio.textContent="115k";
    tdMovimiento.textContent="4";
    tdFuerza.textContent="5";
    tdAgilidad.textContent="5+";
    tdPase.textContent="5+";
    tdArmadura.textContent="10+";
    tdHabilidades.textContent="Siempre Hambriento, Solitario (4+), Golpe Mortífero(+1), Proyectil Vómito,"+
    " Realmente Estúpido, Regeneración, Lanzar Compañero";
    tdPrincipal.textContent="F";
    tdSecundaria.textContent="AGP";
    tr.appendChild(tdCantidad);
    tr.appendChild(tdAlineacion);
    tr.appendChild(tdPrecio);
    tr.appendChild(tdMovimiento);
    tr.appendChild(tdFuerza);
    tr.appendChild(tdAgilidad);
    tr.appendChild(tdPase);
    tr.appendChild(tdArmadura);
    tr.appendChild(tdHabilidades);
    tr.appendChild(tdPrincipal);
    tr.appendChild(tdSecundaria);
    tabla.appendChild(tr);
}

//crear la funcion para crear la tabla
function mostrarEquipoSeleccionado(event){
    let section=document.getElementById("informacionEquipo");
    while(section.children.length>0){
        section.removeChild(section.children[0]);
    }
    let tabla=document.createElement("table");
    let tr=document.createElement("tr");
    aniadeCabeceras(tr);
    tabla.appendChild(tr);
    let reroll=document.createElement("p");
    let apotecario=document.createElement("p");
    let normasEspeciales=document.createElement("p");
    switch (select.value) {
        case "humanos":
            tablaHumanos(tabla);
            reroll.textContent="Reroll: 0-8 50k";
            apotecario.textContent="Apotecario: si";
            normasEspeciales.textContent="Normas Especiales: Clásica del Viejo Mundo";
            break;
        case "orcos":
            tablaOrcos(tabla);
            reroll.textContent="Reroll: 0-8 60k";
            apotecario.textContent="Apotecario: si";
            normasEspeciales.textContent="Normas Especiales: Reyerta en las Yermas";
            break;
    }
    tabla.className="equipo";
    tabla.classList.add("ocupaTodo")
    section.appendChild(tabla);
    section.appendChild(reroll);
    section.appendChild(apotecario);
    section.appendChild(normasEspeciales);
}

function crearEqipo(event){
    location="../html/crearEquipo.html";
}

//acceder al select y al boton
let select=document.getElementById("equipos");
let btn=document.getElementById("btnCrearEquipo");
//aniadir los hijos
let humanos=document.createElement("option");
humanos.text="Humanos";
humanos.value="humanos";
select.appendChild(humanos);
let orcos=document.createElement("option");
orcos.text="Orcos";
orcos.value="orcos";
select.appendChild(orcos);
// dar los eventos
select.addEventListener("change",mostrarEquipoSeleccionado);
btn.addEventListener("click",crearEqipo)
mostrarEquipoSeleccionado()